[package]
name = "aish"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
common = { path = "../common" }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

