[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
common = { path = "../common" }
ctrlc = "3.4"
serde_json = "1.0"
regex = "1.10"

[dev-dependencies]
tempfile = "3.8"

